config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :ballot do
    member do
      get 'create_races'
      get 'instructions'
      get 'completed'
      get 'voters_guide'
    end
  end
  resources :race do
    member do
      # get 'submit_vote_and_go_to_next_race'
      # get 'submit_vote_and_return'
      post 'submit_vote'
    end
  end
  resources :vote 
  resources :demographics 

end

app/models/ballot.rb
class Ballot < ActiveRecord::Base
	has_many :races
	has_one :demographics
end

app/controllers/ballot_controller.rb
class BallotController < ApplicationController

	def index
		@ballots = Ballot.all
	end

	def show
		@ballot = Ballot.find(params[:id])
	end

	def new
		@ballot = Ballot.create()
		t = rand(3);
		if t == 0
			@ballot.organization = "n" #non-sequential
		elsif t == 1
			@ballot.organization = "s" #sequential
		elsif t == 2
			@ballot.organization = "s_exp" #sequential (explicit no-preference)

		end

		theme = rand(2)
		if theme == 0
			@ballot.theme = "rice"
		else
			@ballot.theme = "political"
		end

		@ballot.save
		@dem = Demographics.create()
		@dem.ballot_id = @ballot.id
		@dem.save
		redirect_to "/ballot/#{@ballot.id}/create_races"
	end

	def create
		@ballot = Ballot.new(ballot_params)
		@ballot.save
	end

	def instructions
		@ballot = Ballot.find(params[:id])
		@races = @ballot.races
		@ballot.instructions = "Instructions"
	end

	def completed
		@ballot = Ballot.find(params[:id])
		@ballot.finished_at = Time.now
		@ballot.save
	end

	def voters_guide
		@ballot = Ballot.find(params[:id]) 
		if @ballot.theme == "rice"
			pdf_filename = File.join(Rails.root, "public/Voter's Guide.pdf")
		else
			pdf_filename = File.join(Rails.root, "public/x103 Voter Guide.pdf")
		end
		send_file(pdf_filename, :filename => "voters_guide.pdf", :disposition => 'inline', :type => "application/pdf")
	end

	def create_races
		#create all the races for this ballot
		@ballot = Ballot.find(params[:id])
		@dem = @ballot.demographics

		if @ballot.theme == "political" and @ballot.organization == "s_exp"
			
			#president/vice
			@race = @ballot.races.create(category:"President and Vice President", race_type:"Choose One", title:"President and Vice President", ballot_id: @ballot.id, voted: false);
			@race.candidate.create(name: "Gordon Bearce, Nathan Maclean", party: "REP", race_id: @race.id, selected: false)
			@race.candidate.create(name: "Vernon Stanley Albury, Richard Rigby", party: "DEM", race_id: @race.id, selected: false)
			@race.candidate.create(name: "Janette Froman, Chris Aponte", party: "LIB", race_id: @race.id, selected: false)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)


			#senator
			@race = @ballot.races.create(category:"Congressional", race_type:"Choose One", title:"United States Senator", ballot_id: @ballot.id)
			@race.candidate.create(name: "Cecile Cadieux", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Fern Brzezinski", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "Corey Dery", party: "IND", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#representative
			@race = @ballot.races.create(category:"Congressional", race_type:"Choose One", title:"Representative in Congress", ballot_id: @ballot.id)
			@race.candidate.create(name: "Pedro Brouse", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Robert Mettler", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#governor
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Governor", ballot_id: @ballot.id)
			@race.candidate.create(name: "Glen Travis Lozier", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Rick Stickles", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "Maurice Humble", party: "IND", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#governor
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Lieutenent Governor", ballot_id: @ballot.id)
			@race.candidate.create(name: "Shane Terrio", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Cassie Principe", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#attorney general
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Attorney General", ballot_id: @ballot.id)
			@race.candidate.create(name: "Tim Speight", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Rick Organ", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#comptroller
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Comptroller of Public Accounts", ballot_id: @ballot.id)
			@race.candidate.create(name: "Therese Gustin", party: "IND", race_id: @race.id)
			@race.candidate.create(name: "Greg Converse", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#land office
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Commissioner of General Land Office", ballot_id: @ballot.id)
			@race.candidate.create(name: "Sam Saddler", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Elise Ellzey", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#agriculture
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Commissioner of Agriculture", ballot_id: @ballot.id)
			@race.candidate.create(name: "Polly Rylander", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Roberto Aron", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#railroad
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Railroad Commissioner", ballot_id: @ballot.id)
			@race.candidate.create(name: "Jillian Balas", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Zachary Minick", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#state senator
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"State Senator", ballot_id: @ballot.id)
			@race.candidate.create(name: "Ricardo Nigro", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Wesley Steven Millette", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#state representative
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"State Representative District 134", ballot_id: @ballot.id)
			@race.candidate.create(name: "Petra Bencomo", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Susanne Rael", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#board of education
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Member State Board of Education District 2", ballot_id: @ballot.id)
			@race.candidate.create(name: "Peter Varga", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Mark Baber", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#judge
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Presiding Judge Texas Supreme Court Place 3", ballot_id: @ballot.id)
			@race.candidate.create(name: "Tim Grasty", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#judge
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Presiding Judge Court of Criminal Appeals, Place 2", ballot_id: @ballot.id)
			@race.candidate.create(name: "Dan Plouffe", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Derrick Melgar", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#district attorney
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"District Attorney", ballot_id: @ballot.id)
			@race.candidate.create(name: "Corey Behnke", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Jennifer A. Lundeed", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#county treasurer
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"County Treasurer", ballot_id: @ballot.id)
			@race.candidate.create(name: "Dean Caffee", party: "REP", race_id: @race.id)
			@race.candidate.create(name: "Gordon Kallas", party: "DEM", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)

			#sheriff
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"Sheriff", ballot_id: @ballot.id)
			@race.candidate.create(name: "Stanley Saari", party: "GP", race_id: @race.id)
			@race.candidate.create(name: "Jason Valle", party: "LIB", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)
			#county tax assessor
			@race = @ballot.races.create(category:"State", race_type:"Choose One", title:"County Tax Assessor", ballot_id: @ballot.id)
			@race.candidate.create(name: "Howard Grady", party: "IND", race_id: @race.id)
			@race.candidate.create(name: "Randy H. Clemons", party: "CON", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)
			#justice of the peace
			@race = @ballot.races.create(category:"Nonpartisan", race_type:"Choose One", title:"Justice of the Peace", ballot_id: @ballot.id)
			@race.candidate.create(name: "Deborah Kamps", race_id: @race.id)
			@race.candidate.create(name: "Clyde Gayton Jr.", race_id: @race.id)
			@race.candidate.create(name: "No Preference", race_id: @race.id, selected: false)
			#county judge
			@race = @ballot.races.create(category:"Nonpartisan", race_type:"Choose One", title:"County Judge", ballot_id: @ballot.id)

app/helpers/ballot_helper.rb
module BallotHelper
end

app/views/ballot/completed.html.erb
<div class="center jumbotron">
	<div class="container-fluid"> 
		<p>Thank you for voting!</p>
	</div> 
</div>

app/views/ballot/index.html.erb
<!-- Breakdown of the six: !-->

<% non_seq_total_votes = 0 %>
<% non_seq_total_voters = 0 %>
<% non_seq_total_duration = 0 %>

<% seq_exp_total_votes = 0 %>
<% seq_exp_total_voters = 0 %>
<% seq_exp_total_duration = 0 %>

<% seq_total_votes = 0 %>
<% seq_total_voters = 0 %>
<% seq_total_duration = 0 %>

<% pol_total_votes = 0 %>
<% pol_total_voters = 0 %>
<% pol_total_duration = 0 %>

<% rice_total_votes = 0 %>
<% rice_total_voters = 0 %>
<% rice_total_duration = 0 %>

<!-- Breakdown of the six: !-->

<% rice_non_total_votes = 0 %>
<% rice_non_total_voters = 0 %>
<% rice_non_total_duration = 0 %>

<% pol_non_total_votes = 0 %>
<% pol_non_total_voters = 0 %>
<% pol_non_total_duration = 0 %>

<% rice_seq_total_votes = 0 %>
<% rice_seq_total_voters = 0 %>
<% rice_seq_total_duration = 0 %>

<% pol_seq_total_votes = 0 %>
<% pol_seq_total_voters = 0 %>
<% pol_seq_total_duration = 0 %>

<% rice_seq_ex_total_votes = 0 %>
<% rice_seq_ex_total_voters = 0 %>
<% rice_seq_ex_total_duration = 0 %>

<% pol_seq_ex_total_votes = 0 %>
<% pol_seq_ex_total_voters = 0 %>
<% pol_seq_ex_total_duration = 0 %>

<!-- Per race breakdown !-->
<% political_races = Array.new(27, 0) %>
<% rice_races = Array.new(27, 0) %>

<!-- Average time per race !-->
<% non_seq_races = Array.new(27, 0) %>
<% seq_races = Array.new(27, 0) %>
<% seq_exp_races = Array.new(27, 0) %>
<% prev_seq = 0 %>
<% prev_seq_exp = 0 %>

<% males = 0 %>
<% females = 0 %>
<% age = 0 %>
<% age_count = 0 %>


<!-- timing data !-->
<% non_seq_votes = Array.new(40, 0) %>
<% seq_votes = Array.new(40, 0) %>
<% seq_exp_votes = Array.new(40, 0) %>
<% ballot_num = 0 %>

<% @ballots.each do |ballot| %>

	<% next if ballot.id == 66 || ballot.id == 87 || ballot.id == 89 || ballot.id == 96 || ballot.id == 99 || ballot.id == 98 || ballot.id == 97 || ballot.id == 47 || ballot.id == 52 %>
	<%= ballot.id %></br>
	<%= ballot.theme %></br>
	<%= ballot.organization %></br>
	<% if ballot.finished_at != nil %>
		<%= distance_of_time_in_words(ballot.created_at, ballot.finished_at) %>
	<% end %>
	<% @races = ballot.races.order(:created_at) %>
	<% @demographics = ballot.demographics %>

	<% if @demographics %>
		<% if @demographics.gender == "male" %>
			<% males = males + 1 %>
		<% elsif @demographics.gender == "female" %>
			<% females = females + 1 %>
		<% end %>
		<% if @demographics.age %>
			<% age = age + @demographics.age %>
			<% age_count = age_count + 1 %>
		<% end %>
	<% end %>

	<% count = 0 %>
	<% no_preference = 0 %>

	<% position = 0 %>
	<% last_race = nil %>
	<% @races.each do |r| %>
		<% if position == 0 %>
			<%= r.title %>
		<% end %>
		<% if r.vote != nil %>
			<% if ballot.theme == "political" %>
				<% political_races[position] = political_races[position] + 1 %>
			<% else %>
				<% rice_races[position] = rice_races[position] + 1 %>
			<% end %>

			<% if ballot.organization == "n" %>

			<% elsif ballot.organization == "s_expl_after" %>
				<% if position == 0 %>
					<% prev_seq = (r.updated_at - @demographics.updated_at) %>
				<% else %>
					<% prev_seq = (r.updated_at - last_race.updated_at) %>
				<% end %>
				<% seq_races[position] = seq_races[position] + prev_seq %>
			<% elsif ballot.organization == "s_after" %>
				<% if position == 0 %>
					<% prev_seq_exp = (r.updated_at - @demographics.updated_at) %>
				<% else %>
					<% prev_seq_exp = (r.updated_at - last_race.updated_at) %>
				<% end %>
				<% seq_exp_races[position] = seq_races[position] + prev_seq_exp %>
			<% end %>

			<% count = count + 1 %>
			<% if r.vote.candidate == "No Preference"%>
				<% no_preference = no_preference + 1 %>
			<% end %>

		<% end %>
		<% position = position + 1 %>
		<% last_race = r %>
	<% end %>

	<% if ballot.organization == "n" %>
		<% non_seq_total_voters = non_seq_total_voters + 1 %>
		<% non_seq_total_votes = non_seq_total_votes + count %>
		<% if ballot.finished_at != nil %>
			<% non_seq_total_duration = non_seq_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
		<% end %>

		<% if ballot.theme == "political" %>
			<% non_seq_votes[ballot_num] = count %>
			<% pol_non_total_voters = pol_non_total_voters + 1 %>
			<% pol_non_total_votes = pol_non_total_votes + count %>
			<% if ballot.finished_at != nil %>
				<% pol_non_total_duration = pol_non_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
			<% end %>
		<% else %>
			<% rice_non_total_voters = rice_non_total_voters + 1 %>
			<% rice_non_total_votes = rice_non_total_votes + count %>
			<% if ballot.finished_at != nil %>
				<% rice_non_total_duration = rice_non_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
			<% end %>
		<% end %>
	<% end %>

	<% if ballot.organization == "s_expl_after" %>
		<% seq_exp_total_voters = seq_exp_total_voters + 1 %>
		<% seq_exp_total_votes = seq_exp_total_votes + count - no_preference %>
		<% if ballot.finished_at != nil %>
			<% seq_exp_total_duration = seq_exp_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
		<% end %>

		<% if ballot.theme == "political" %>
			<% seq_exp_votes[ballot_num] = count - no_preference %>
			<% pol_seq_ex_total_voters = pol_seq_ex_total_voters + 1 %>
			<% pol_seq_ex_total_votes = pol_seq_ex_total_votes + count - no_preference %>
			<% if ballot.finished_at != nil %>
				<% pol_seq_ex_total_duration = pol_seq_ex_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
			<% end %>
		<% else %>
			<% rice_seq_ex_total_voters = rice_seq_ex_total_voters + 1 %>
			<% rice_seq_ex_total_votes = rice_seq_ex_total_votes + count - no_preference %>
			<% if ballot.finished_at != nil %>
				<% rice_seq_ex_total_duration = rice_seq_ex_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
			<% end %>
		<% end %>
	<% end %>

	<% if ballot.organization == "s_after" %>
		<% seq_total_voters = seq_total_voters + 1 %>
		<% seq_total_votes = seq_total_votes + count %>
		<% if ballot.finished_at != nil %>
			<% seq_total_duration = seq_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
		<% end %>

		<% if ballot.theme == "political" %>
			<% seq_votes[ballot_num] = count %>
			<% pol_seq_total_voters = pol_seq_total_voters + 1 %>
			<% pol_seq_total_votes = pol_seq_total_votes + count %>
			<% if ballot.finished_at != nil %>
				<% pol_seq_total_duration = pol_seq_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
			<% end %>
		<% else %>
			<% rice_seq_total_voters = rice_seq_total_voters + 1 %>
			<% rice_seq_total_votes = rice_seq_total_votes + count %>
			<% if ballot.finished_at != nil %>
				<% rice_seq_total_duration = rice_seq_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
			<% end %>
		<% end %>
	<% end %>

	<% if ballot.theme == "rice" %>
		<% rice_total_voters = rice_total_voters + 1 %>
		<% rice_total_votes = rice_total_votes + count - no_preference%>
		<% if ballot.finished_at != nil %>
			<% rice_total_duration = rice_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
		<% end %>
	<% end %>

	<% if ballot.theme == "political" %>
		<% pol_total_voters = pol_total_voters + 1 %>
		<% pol_total_votes = pol_total_votes + count - no_preference %>
		<% if ballot.finished_at != nil %>
			<% pol_total_duration = pol_total_duration + ((ballot.finished_at - ballot.created_at)/60).round %>
		<% end %>
	<% end %>

	</br>Voted in: <%= count %>/<%= @races.count %> races</br>
	<% if ballot.organization == "s_expl_after" || ballot.organization == "s_exp" %>
		Voted "No Preference" <%= no_preference %> times</br>
	<% end %>
	
	</br>
	<% ballot_num = ballot_num + 1 %>
<% end %>

<p><b>Non Sequential Data:</b></p>
<p>Number of Voters: <%= non_seq_total_voters %></p>
<p>Average # of votes: <%= non_seq_total_votes / non_seq_total_voters.to_f %></p>
<p>Average duration: <%= non_seq_total_duration / non_seq_total_voters %></p></br>

<p><b>Sequential Explicit Data:</b></p>
<p>Number of Voters: <%= seq_exp_total_voters %></p>
<p>Average # of votes: <%= seq_exp_total_votes / seq_exp_total_voters.to_f %></p>
<p>Average duration: <%= seq_exp_total_duration / seq_exp_total_voters %></p></br>

<p><b>Sequential Data:</b></p>
<p>Number of Voters: <%= seq_total_voters %></p>
<p>Average # of votes: <%= seq_total_votes / seq_total_voters.to_f %></p>
<p>Average duration: <%= seq_total_duration / seq_total_voters %></p></br>

<p><b>Rice Data:</b></p>
<p>Number of Voters: <%= rice_total_voters %></p>
<p>Average # of votes: <%= rice_total_votes / rice_total_voters.to_f %></p>
<p>Average duration: <%= rice_total_duration / rice_total_voters %></p></br>

<p><b>Political Data:</b></p>
<p>Number of Voters: <%= pol_total_voters %></p>
<p>Average # of votes: <%= pol_total_votes / pol_total_voters.to_f %></p>
<p>Average duration: <%= pol_total_duration / pol_total_voters %></p></br>

<!-- Six Breakdown: !-->

<p><b>Rice Non Data:</b></p>
<p>Number of Voters: <%= rice_non_total_voters %></p>
<p>Average # of votes: <%= rice_non_total_votes / rice_non_total_voters.to_f %></p>
<p>Average duration: <%= rice_non_total_duration / rice_non_total_voters %></p></br>

<p><b>Pol Non Data:</b></p>
<p>Number of Voters: <%= pol_non_total_voters %></p>
<p>Average # of votes: <%= pol_non_total_votes / pol_non_total_voters.to_f %></p>
<p>Average duration: <%= pol_non_total_duration / pol_non_total_voters %></p></br>

<p><b>Rice Seq Data:</b></p>
<p>Number of Voters: <%= rice_seq_total_voters %></p>
<p>Average # of votes: <%= rice_seq_total_votes / rice_seq_total_voters.to_f %></p>
<p>Average duration: <%= rice_seq_total_duration / rice_seq_total_voters %></p></br>

<p><b>Pol Seq Data:</b></p>
<p>Number of Voters: <%= pol_seq_total_voters %></p>
<p>Average # of votes: <%= pol_seq_total_votes / pol_seq_total_voters.to_f %></p>
<p>Average duration: <%= pol_seq_total_duration / pol_seq_total_voters %></p></br>

<p><b>Rice Seq Ex Data:</b></p>
<p>Number of Voters: <%= rice_seq_ex_total_voters %></p>
<p>Average # of votes: <%= rice_seq_ex_total_votes / rice_seq_ex_total_voters.to_f %></p>
<p>Average duration: <%= rice_seq_ex_total_duration / rice_seq_ex_total_voters %></p></br>

<p><b>Pol Seq Ex Data:</b></p>
<p>Number of Voters: <%= pol_seq_ex_total_voters %></p>
<p>Average # of votes: <%= pol_seq_ex_total_votes / pol_seq_ex_total_voters.to_f %></p>
<p>Average duration: <%= pol_seq_ex_total_duration / pol_seq_ex_total_voters %></p></br>

<% rice_races.collect { |n| n / rice_total_voters.to_f } %>
<% political_races.collect { |n| n / pol_total_voters.to_f } %>
<% new_seq = seq_races.collect { |n| n / seq_total_voters.to_f } %>
<% new_seq_exp = seq_exp_races.collect { |n| n / seq_exp_total_voters.to_f } %>

<p>Political Races: <%= political_races.to_s %></p></br>
<p>Rice Races: <%= rice_races.to_s %></p></br>

<p>Seq Times: <%= new_seq.to_s %></p></br>
<p>Seq Exp Times: <%= new_seq_exp.to_s %></p></br>

<p>Males: <%= males %></p></br>
<p>Females: <%= females %></p></br>
<p>Age: <%= age / age_count.to_f %></p></br>

<p>n-Seq votes: <%= non_seq_votes.to_s %></p></br>
<p>Seq Exp votes: <%= seq_exp_votes.to_s %></p></br>
<p>Seq votes: <%= seq_votes.to_s %></p></br>

app/views/ballot/show.html.erb
<div class"container-fluid">
	<div class="jumbotron center">
		<h1>Ballot Overview</h1>
		<br>
		<table class="table table-hover">
		<% @ballot.races.order(:created_at).each do |r| %>
				<tr>
					<% if r.voted == true %> 
						<td class="success"id="race#{r}"><h3><%=link_to r.title, race_path(r)%></h3></td>
					<% else %>
						<td id="race#{r}"><h3><%=link_to r.title, race_path(r)%></h3></td>
					<% end %>		
    			<tr/>
    	<% end%>
    	</table>
    	<br>
    	<br>
		<%= link_to "Submit", "/ballot/#{@ballot.id}/completed", class: "btn btn-lg btn-success center" %>
</div>